### ISSUE TITLE
Support Breeze Dark theme

### ISSUE THREAD

**Issue by mfs85** [z000ao8q/audios#553]
**Describe the bug**
1. Some items are not clearly visible, when using the Breeze Dark theme.
Is there something that could be done? At least Menu (Titles, Artist, Playlists, e.g.), progress bar and volume bar is having this issue.

2. The name of the app is too long and it "overwrites" the names on other apps

**To Reproduce**
1. Enable Breeze Dark theme
2. Click on Audio Player
3. Move the cursor to the Audio Player logo

**Expected behavior**
1. To see items clearly when using Breeze Dark theme.
2. To see app names without overwriting other names

**Screenshots**
![image](https://user-images.githubusercontent.com/80595408/136390660-44361b19-ee54-4878-bd18-c2c889cc5589.png)

**Versions:**
 - Nextcloud: 21.0.5
 - Audioplayer 3.2.2
 
**Nextcloud log**
-

**Comment by Rello** [comment]
Hello,
the issue I see here are the errors in the category dropdrown.
the topic with the overlapping app title is standard Nextcloud behavior. it works this way when app names are longer

**Comment by Rello** [comment]
Hello,
do you have any other theming?
because NC dark theme shows correctly (dropdown) for me.
also the header should be blue 

![Bildschirmfoto 2021-12-16 um 21 23 11](https://user-images.githubusercontent.com/13385119/146443842-306d492e-7f99-4707-9cda-416bdb36474c.png)

**Comment by mfs85** [comment]
No, only this Breeze Dark theme is enabled.
If I deactivate it, I will have light color and header will also changed to blue.

![image](https://user-images.githubusercontent.com/80595408/146558692-29f3eaf1-6024-4534-bd9b-83e5345c066d.png)

**Comment by yaroslav4167** [comment]
i created css styles for fix this. (i use stylus plugin for my firefox) but, you may insert this css code in Custom Styling field.

```css
/*Deploying playlist was hidden under the page*/
.coverrow {
    padding-bottom: 250px;
}

/*** Breeze dark audioplayer fixes ***/
/*In dark mode there is no progress bar */
.theme--dark.theme--breezedark #progressBar,
.volume-slider::-moz-range-track {
    background: #cccccc3d !important;
}

.theme--dark.theme--breezedark .volume-slider::-webkit-slider-progress, 
.theme--dark.theme--breezedark .volume-slider::-moz-range-progress {
    background-color: #0082c9;
    padding: 2px;
    border-radius: 5px;
}

/*Selecting the type of sorting*/
.theme--dark.theme--breezedark #category_selector {
    background-image: none !important;
    margin: 7px 0 !important;
}
```
